name: clustering_iaf_vae
batch_size: 128
lr: 0.0001
num_epochs: 200
hidden_size: 1000
latent_size: 2
criterion: mse
bn: True

kld_weight: 0.01
kld_schedule: linear
kld_warmup: False

n_clusters: 20
eta: 1.5

context_size: 10
p_weight: 1

noise_sigma: 0