name: diff_vae_clustering
batch_size: 128
lr: 0.0001
num_epochs: 200
hidden_size: 1000
latent_size: 2
criterion: bce
bn: True

kld_weight: 0.01
kld_schedule: linear
kld_warmup: False

diff_weight: 10

timesteps: 20

endtoend: False

n_clusters: 20
eta: 50

discrete_decode: False

noise_sigma: 0