name: h_iaf_vae
batch_size: 128
lr: 0.0001
num_epochs: 200
hidden_size: 1000
latent_size: 2
criterion: bce
bn: False

kld_weight: 0.005
kld_schedule: linear
kld_warmup: False

context_size: 10
p_weight: 0.5

noise_sigma: 0